#!/system/bin/sh
#Debug early suspend
#echo "15" > /sys/module/wakelock/parameters/debug_mask
#echo "15" > /sys/module/userwakelock/parameters/debug_mask
#echo "15" > /sys/module/earlysuspend/parameters/debug_mask

#LPx Suspend mode
#switch to lp1 because r15 and r16 have lp0 harmony issues
#echo "lp1" > /sys/power/suspend/mode

#Cpuquiet
#echo "balance" > /sys/devices/system/cpu/cpuquiet/current_governor

#Power tweaks
#echo "1500" > /proc/sys/vm/dirty_writeback_centisecs
#echo "auto" > /sys/bus/usb/devices/1-1.2/power/level
#echo "auto" > /sys/bus/usb/devices/1-1.1/power/level
#echo "auto" > /sys/bus/usb/devices/2-1.3/power/level
