#!/system/bin/sh
#
# Load Additional kernel modules
#
# Asix usb ethernet devices
insmod /system/lib/modules/asix.ko
# Sony joysticks support
insmod /system/lib/modules/hid-sony.ko
# USB Audio support
insmod /system/lib/modules/snd-hwdep.ko
insmod /system/lib/modules/snd-usbmidi-lib.ko
insmod /system/lib/modules/snd-usb-audio.ko
#
# Add additional modules here
